{{- if not .Values.modelmesh.namespaceScopeMode }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "modelmesh.labels" . | nindent 4 }}
  name: modelmesh-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: modelmesh-controller-role
subjects:
- kind: ServiceAccount
  name: modelmesh-controller
  namespace: {{ .Release.Namespace }}
{{- end }}