apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "modelmesh.labels" . | nindent 4 }}
  name: {{ .Values.modelmesh.config.configMapName }}
data:
  config-defaults.yaml: |
    podsPerRuntime: {{ .Values.modelmesh.config.podsPerRuntime }}
    headlessService: true
    modelMeshImage:
      name: {{ .Values.modelmesh.config.modelmeshImage }}
      tag: {{ .Values.modelmesh.config.modelmeshImageTag }}
    modelMeshResources:
      requests:
        cpu: "300m"
        memory: "448Mi"
      limits:
        cpu: "3"
        memory: "448Mi"
    restProxy:
      enabled: true
      port: 8008
      image:
        name: {{ .Values.modelmesh.config.restProxyImage }}
        tag: {{ .Values.modelmesh.config.restProxyImageTag }}
      resources:
        requests:
          cpu: "50m"
          memory: "96Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
    storageHelperImage:
      name: {{ .Values.modelmesh.config.modelmeshRuntimeAdapterImage }}
      tag: {{ .Values.modelmesh.config.modelmeshRuntimeAdapterImageTag }}
      command: ["/opt/app/puller"]
    storageHelperResources:
      requests:
        cpu: "50m"
        memory: "96Mi"
      limits:
        cpu: "2"
        memory: "512Mi"
    serviceAccountName: ""
    metrics:
      enabled: true
    builtInServerTypes:
      - triton
      - mlserver
      - ovms
      - torchserve
