apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "modelmesh.labels" . | nindent 4 }}
  name: modelmesh-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "modelmesh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "modelmesh.labels" . | nindent 8 }}
    spec:
      {{- with .Values.modelmesh.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.modelmesh.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.modelmesh.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.modelmesh.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        {{- if .Values.modelmesh.config.devModeLogging }}
        - name: DEV_MODE_LOGGING
          value: {{ .Values.modelmesh.config.devModeLogging | quote }}
        {{- end }}
        - name: NAMESPACE_SCOPE
          value: {{ .Values.modelmesh.namespaceScopeMode | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_SECRET_NAME
          value: "model-serving-etcd"
        image: {{ .Values.modelmesh.controller.image }}:{{ .Values.modelmesh.controller.tag }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        name: manager
        ports:
        - containerPort: 9443
          name: webhook
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 96Mi
        securityContext:
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/model-serving/config/default
          name: config-defaults
          readOnly: true
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: modelmesh-webhook-server-cert
          readOnly: true
      serviceAccountName: modelmesh-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config-defaults
        configMap:
          defaultMode: 420
          name: {{ .Values.modelmesh.config.configMapName }}
      - name: modelmesh-webhook-server-cert
        secret:
          defaultMode: 420
          secretName: {{ .Values.modelmesh.certmanager.secretName }}
