apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "modelmesh.labels" . | nindent 4 }}
  name: modelmesh

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "modelmesh.labels" . | nindent 4 }}
  name: modelmesh-controller
