apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "modelmesh.labels" . | nindent 4 }}
  name: modelmesh-webhook-server-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: webhook
  selector:
    {{- include "modelmesh.selectorLabels" . | nindent 4 }}
