{
 "title": "ModelMesh Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "my-namespace" },
   { "name": "servicename", "query": "my-service-name" },
   {
    "name": "mm_container",
    "label": "MM Container Name",
    "query": "mm,mm-runtime,modelmesh-runtime"
   }
  ]
 },
 "panels": [
  {
   "title": "Global LRU age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(modelmesh_instance_lru_age_seconds{namespace=\"$namespace\",pod=~\"$servicename-.*\"})",
     "legendFormat": "LRU Age"
    },
    {
     "expr": "max(rate(modelmesh_age_at_eviction_milliseconds_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval])/rate(modelmesh_age_at_eviction_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))/1000",
     "legendFormat": "Age at Eviction"
    }
   ]
  },
  {
   "title": "Cluster capacity and utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(modelmesh_instance_used_bytes{namespace=\"$namespace\",pod=~\"$servicename-.*\"}/1024)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(modelmesh_instance_capacity_bytes{namespace=\"$namespace\",pod=~\"$servicename-.*\"}/1024)",
     "legendFormat": "Total Cache Capacity"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$servicename-.*\",container=\"$mm_container\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Model Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(modelmesh_models_managed_total{namespace=\"$namespace\",pod=~\"$servicename-.*\"})",
     "legendFormat": "managed models"
    },
    {
     "expr": "max(modelmesh_models_loaded_total{namespace=\"$namespace\",pod=~\"$servicename-.*\"})",
     "legendFormat": "loaded models"
    },
    {
     "expr": "max(modelmesh_models_with_failure_total{namespace=\"$namespace\",pod=~\"$servicename-.*\"})",
     "legendFormat": "models with load failure"
    }
   ]
  },
  {
   "title": "Model Counts per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(modelmesh_instance_models_total{namespace=\"$namespace\",pod=~\"$servicename-.*\"}, \"short_podname\", \"$1\", \"pod\", \"$servicename-(.*)\")",
     "legendFormat": "{{short_podname}}"
    }
   ]
  },
  {
   "title": "Inference API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(modelmesh_api_request_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "External API"
    },
    {
     "expr": "sum(rate(modelmesh_invoke_model_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Internal API"
    }
   ]
  },
  {
   "title": "Average Inference Request and Response Sizes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(modelmesh_request_size_bytes_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))/avg(rate(modelmesh_request_size_bytes_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Request Size"
    },
    {
     "expr": "avg(rate(modelmesh_response_size_bytes_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))/avg(rate(modelmesh_response_size_bytes_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Response Size"
    }
   ]
  },
  {
   "title": "External Inference API Request Rate Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum by (pod)(rate(modelmesh_api_request_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[1m])), \"short_podname\", \"$1\", \"pod\", \"$servicename-(.*)\")",
     "legendFormat": "{{short_podname}}"
    }
   ]
  },
  {
   "title": "External Inference API Response Times by Pod (excluding errors)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(rate(modelmesh_api_request_milliseconds_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\",code=\"OK\"}[$__rate_interval])/rate(modelmesh_api_request_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\",code=\"OK\"}[$__rate_interval]), \"short_podname\", \"$1\", \"pod\", \"$servicename-(.*)\")",
     "legendFormat": "{{short_podname}}"
    }
   ]
  },
  {
   "title": "Internal Inference API Requests Rate Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(rate(modelmesh_invoke_model_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]), \"short_podname\", \"$1\", \"pod\", \"$servicename-(.*)\")",
     "legendFormat": "{{short_podname}}"
    }
   ]
  },
  {
   "title": "Internal Inference API Response Time By Pod (excluding errors)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(\n    rate(modelmesh_invoke_model_milliseconds_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\",code=\"OK\"}[$__rate_interval]) /\n    rate(modelmesh_invoke_model_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\",code=\"OK\"}[$__rate_interval]),\n    \"short_podname\", \"$1\", \"pod\", \"$servicename-(.*)\")",
     "legendFormat": "{{short_podname}}"
    }
   ]
  },
  {
   "title": "Inference API Queue Delay Time By Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(rate(modelmesh_req_queue_delay_milliseconds_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[5m])/rate(modelmesh_req_queue_delay_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[5m]), \"short_podname\", \"$1\", \"pod\", \"$servicename-(.*)\")\n",
     "legendFormat": "{{short_podname}}"
    }
   ]
  },
  {
   "title": "Cache Misses (per 10min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(modelmesh_cache_miss_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(modelmesh_cache_miss_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))/sum(increase(modelmesh_api_request_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Cache Miss Rate"
    }
   ]
  },
  {
   "title": "Cache Miss Delay (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(modelmesh_cache_miss_milliseconds_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[5m]))/avg(rate(modelmesh_cache_miss_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[5m]))",
     "legendFormat": "Cache miss delay"
    }
   ]
  },
  {
   "title": "Model Loads/Unloads (per 5min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(modelmesh_loadmodel_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Model Loads"
    },
    {
     "expr": "-sum(increase(modelmesh_unloadmodel_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Model Unloads"
    },
    {
     "expr": "-sum(increase(modelmesh_age_at_eviction_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Model Evictions"
    },
    {
     "expr": "sum(increase(modelmesh_loadmodel_failure{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Load Failures"
    }
   ]
  },
  {
   "title": "Loaded Model Sizes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(modelmesh_loaded_model_size_bytes_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))/avg(rate(modelmesh_loaded_model_size_bytes_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Loaded Model Size"
    }
   ]
  },
  {
   "title": "Model Loading Times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(modelmesh_loadmodel_milliseconds_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))/avg(rate(modelmesh_loadmodel_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Loading Time"
    },
    {
     "expr": "avg(rate(modelmesh_model_sizing_milliseconds_sum{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))/avg(rate(modelmesh_model_sizing_milliseconds_count{namespace=\"$namespace\",pod=~\"$servicename-.*\"}[$__rate_interval]))",
     "legendFormat": "Sizing Time"
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true
  },
  {
   "title": "ModelMesh Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$servicename-.*\", container=\"$mm_container\"}[$__rate_interval]), \"short_podname\", \"$1\", \"pod\",\"$servicename-(.*)\")",
     "legendFormat": "{{short_podname}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$servicename-.*\",container=\"$mm_container\"})",
     "legendFormat": "Allocation"
    }
   ]
  },
  {
   "title": "Model Mesh Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "label_replace(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$servicename-.*\", container=\"$mm_container\"}/1024/1024,\"short_podname\", \"$1\", \"pod\",\"$servicename-(.*)\")",
     "legendFormat": "{{short_podname}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$mm_container\",pod=~\"$servicename-.*\"}/1024/1024)",
     "legendFormat": "Allocation"
    }
   ]
  },
  {
   "title": "Serving Runtime Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$servicename-.*\",container!=\"$mm_container\",container!=\"\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$servicename-.*\",container!=\"$mm_container\",container!=\"\"}",
     "legendFormat": "{{container}}-alloc"
    }
   ]
  },
  {
   "title": "Serving Runtime Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "label_replace(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$servicename-.*\",container!=\"$mm_container\",container!=\"\"}/1024/1024,\"short_podname\", \"$1\", \"pod\",\"$servicename-(.*)\")",
     "legendFormat": "{{short_podname}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\",container!=\"$mm_container\",container!=\"\",pod=~\"$servicename-.*\"}/1024/1024)",
     "legendFormat": "Allocation"
    }
   ]
  }
 ]
}